package vpn

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
	"net"
	"strings"

	"golang.org/x/crypto/curve25519"

	"github.com/valve-tech/valve-node-app/internal/executor"
)

// PeerKey is a WireGuard (Curve25519) keypair, base64-std encoded like `wg`.
type PeerKey struct{ PrivateKey, PublicKey string }

// GenerateKey mints a WireGuard keypair in pure Go using
// golang.org/x/crypto/curve25519 (it is already a direct dependency). No
// shelling out — the peer key is generated here and delivered to the device
// once via the client config. Generating locally, rather than on the server,
// keeps the device's private half from ever transiting the server host.
func GenerateKey() (PeerKey, error) {
	return generateKeyFrom(rand.Reader)
}

// generateKeyFrom is GenerateKey with an injectable randomness source, so tests
// are deterministic. The private key is 32 bytes of randomness clamped exactly
// as WireGuard/`wg genkey` clamps it (the low 3 bits and high 2 bits are fixed
// so the scalar lands in the correct Curve25519 subgroup); the public key is
// its scalar-base-mult. Matching `wg`'s clamping is what makes a key we mint
// here interoperable with a peer generated by the tool.
func generateKeyFrom(rand io.Reader) (PeerKey, error) {
	var priv [32]byte
	if _, err := io.ReadFull(rand, priv[:]); err != nil {
		return PeerKey{}, fmt.Errorf("vpn: reading randomness for peer key: %w", err)
	}
	priv[0] &= 248
	priv[31] &= 127
	priv[31] |= 64

	pub, err := curve25519.X25519(priv[:], curve25519.Basepoint)
	if err != nil {
		return PeerKey{}, fmt.Errorf("vpn: deriving peer public key: %w", err)
	}
	return PeerKey{
		PrivateKey: base64.StdEncoding.EncodeToString(priv[:]),
		PublicKey:  base64.StdEncoding.EncodeToString(pub),
	}, nil
}

// NextPeerIP returns the next free host address, as "x.x.x.x/32", within the
// server's subnet — skipping the network address, the broadcast address, the
// server's own address, and anything in `taken`. serverCIDR looks like
// "10.9.0.1/24". Entries in `taken` are accepted with OR without a /mask, since
// callers assemble that list from wherever addresses were recorded (a bare IP,
// a /32 from an AllowedIPs line). Errors if the subnet is exhausted — better a
// loud failure than silently reusing an address and blackholing a device.
func NextPeerIP(serverCIDR string, taken []string) (string, error) {
	serverIP, ipnet, err := net.ParseCIDR(strings.TrimSpace(serverCIDR))
	if err != nil {
		return "", fmt.Errorf("vpn: server address %q must be a CIDR like 10.9.0.1/24: %w", serverCIDR, err)
	}

	// Reserved set, keyed by canonical string form: the server's own address
	// plus every taken entry, mask stripped so "10.9.0.3" and "10.9.0.3/32"
	// collide as they should.
	reserved := map[string]bool{serverIP.String(): true}
	for _, t := range taken {
		if ip := parseHost(t); ip != nil {
			reserved[ip.String()] = true
		}
	}

	// The network and broadcast addresses of the subnet are never host
	// addresses. (For a /31 or /32 there are effectively none free; the loop
	// simply falls through to the exhaustion error.)
	network := ipnet.IP
	broadcast := broadcastAddr(ipnet)

	for ip := cloneIP(network); ipnet.Contains(ip); ip = incIP(ip) {
		if ip.Equal(network) || (broadcast != nil && ip.Equal(broadcast)) {
			continue
		}
		if reserved[ip.String()] {
			continue
		}
		return ip.String() + "/32", nil
	}
	return "", fmt.Errorf("vpn: subnet %s is exhausted — no free host address left", ipnet.String())
}

// parseHost accepts either a bare IP or a CIDR and returns the host IP, or nil
// if neither parses. Used to normalize `taken` entries.
func parseHost(s string) net.IP {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	if strings.Contains(s, "/") {
		ip, _, err := net.ParseCIDR(s)
		if err != nil {
			return nil
		}
		return ip
	}
	return net.ParseIP(s)
}

// broadcastAddr is the all-host-bits-set address of an IPv4 subnet; nil for
// IPv6, which has no broadcast address to reserve.
func broadcastAddr(n *net.IPNet) net.IP {
	ip4 := n.IP.To4()
	if ip4 == nil {
		return nil
	}
	b := make(net.IP, net.IPv4len)
	for i := 0; i < net.IPv4len; i++ {
		b[i] = ip4[i] | ^n.Mask[i]
	}
	return b
}

func cloneIP(ip net.IP) net.IP {
	if ip4 := ip.To4(); ip4 != nil {
		out := make(net.IP, net.IPv4len)
		copy(out, ip4)
		return out
	}
	out := make(net.IP, len(ip))
	copy(out, ip)
	return out
}

// incIP returns ip+1, big-endian, in place-safe form.
func incIP(ip net.IP) net.IP {
	out := cloneIP(ip)
	for i := len(out) - 1; i >= 0; i-- {
		out[i]++
		if out[i] != 0 {
			break
		}
	}
	return out
}

// AddPeerParams authorizes one device on a running server.
type AddPeerParams struct {
	Iface         string // server interface on the host, e.g. "jumpgate0"
	PeerPublicKey string // the device's PUBLIC key (base64)
	AllowedIP     string // the /32 to route to this device, e.g. "10.9.0.2/32"
}

// AddPeer authorizes a device on the RUNNING server, persists it so it survives
// a restart, then VERIFIES the peer is actually present. Runs over the executor
// (local or SSH — one path, the same seam every other host operation uses).
//
// The two untrusted-to-a-shell values, PeerPublicKey and AllowedIP, are
// validated BEFORE anything runs: the key must be base64 of exactly 32 bytes
// and the IP a single-host /32 CIDR. That both rejects garbage early and closes
// the shell-injection door, since these values are interpolated into `wg set`.
//
// It VERIFIES rather than trusts: `wg set` can exit 0 without the peer landing
// (a malformed key it tolerates, a race on save), so success is reported only
// after `wg show <iface> dump` lists this public key. This app's recurring
// failure mode is success reported over a broken state.
func AddPeer(ctx context.Context, exec executor.Executor, p AddPeerParams) error {
	if !validIfaceName(p.Iface) {
		return fmt.Errorf("vpn: interface name %q is invalid — up to 15 of letters, digits, dot, dash or underscore", p.Iface)
	}
	if err := validateWGKey(p.PeerPublicKey); err != nil {
		return fmt.Errorf("vpn: peer public key: %w", err)
	}
	if err := validateHost32(p.AllowedIP); err != nil {
		return fmt.Errorf("vpn: allowed IP: %w", err)
	}

	// 1. Authorize on the live interface.
	set := fmt.Sprintf("wg set %s peer %s allowed-ips %s",
		shellArg(p.Iface), shellArg(p.PeerPublicKey), shellArg(p.AllowedIP))
	if res, err := exec.Run(ctx, set, nil); err != nil {
		return fmt.Errorf("vpn: wg set: %w", err)
	} else if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg set exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}

	// 2. Persist the running config to /etc/wireguard/<iface>.conf so the peer
	//    survives a restart — an in-memory-only authorization is a peer that
	//    silently vanishes on the next reboot.
	if res, err := exec.Run(ctx, "wg-quick save "+shellArg(p.Iface), nil); err != nil {
		return fmt.Errorf("vpn: wg-quick save: %w", err)
	} else if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg-quick save exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}

	// 3. VERIFY the peer is really there before claiming success.
	res, err := exec.Run(ctx, "wg show "+shellArg(p.Iface)+" dump", nil)
	if err != nil {
		return fmt.Errorf("vpn: wg show dump: %w", err)
	}
	if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg show dump exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}
	if !dumpHasPeer(res.Stdout, p.PeerPublicKey) {
		return fmt.Errorf("vpn: wg set reported success but peer %q is not present on %q", p.PeerPublicKey, p.Iface)
	}
	return nil
}

// RemovePeer revokes a device: removes it from the running server, persists the
// removal so it does not come back on a restart, and VERIFIES it is gone. It is
// idempotent — revoking a peer that is not there is not an error, because the
// end state (that device cannot connect) is exactly what was asked for. The one
// shell-bound value, the public key, is validated first for the same reason
// AddPeer validates it.
func RemovePeer(ctx context.Context, exec executor.Executor, iface, peerPublicKey string) error {
	if !validIfaceName(iface) {
		return fmt.Errorf("vpn: interface name %q is invalid — up to 15 of letters, digits, dot, dash or underscore", iface)
	}
	if err := validateWGKey(peerPublicKey); err != nil {
		return fmt.Errorf("vpn: peer public key: %w", err)
	}

	remove := fmt.Sprintf("wg set %s peer %s remove", shellArg(iface), shellArg(peerPublicKey))
	if res, err := exec.Run(ctx, remove, nil); err != nil {
		return fmt.Errorf("vpn: wg set peer remove: %w", err)
	} else if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg set peer remove exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}
	if res, err := exec.Run(ctx, "wg-quick save "+shellArg(iface), nil); err != nil {
		return fmt.Errorf("vpn: wg-quick save: %w", err)
	} else if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg-quick save exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}

	// VERIFY the peer is really gone — a revoke that silently left the device
	// authorized is the worst possible outcome of this call.
	res, err := exec.Run(ctx, "wg show "+shellArg(iface)+" dump", nil)
	if err != nil {
		return fmt.Errorf("vpn: wg show dump: %w", err)
	}
	if res.ExitCode != 0 {
		return fmt.Errorf("vpn: wg show dump exited %d: %s", res.ExitCode, firstLine(res.Stderr))
	}
	if dumpHasPeer(res.Stdout, peerPublicKey) {
		return fmt.Errorf("vpn: wg set peer remove reported success but peer %q is still present on %q", peerPublicKey, iface)
	}
	return nil
}

// dumpHasPeer reports whether `wg show <iface> dump` lists a peer whose public
// key (the first field of each peer line) equals pub. Matching the field rather
// than a naive Contains avoids a false positive from the key appearing inside,
// say, an endpoint or preshared-key column.
func dumpHasPeer(dump, pub string) bool {
	lines := strings.Split(strings.TrimRight(dump, "\n"), "\n")
	if len(lines) < 2 {
		return false // just the interface line (or empty) — no peers
	}
	for _, line := range lines[1:] { // skip the interface line
		fields := strings.Split(line, "\t")
		if len(fields) >= 1 && strings.TrimSpace(fields[0]) == pub {
			return true
		}
	}
	return false
}

// validateWGKey requires a base64-std string decoding to exactly 32 bytes — a
// WireGuard key's size. Anything else is rejected before it can reach a shell.
func validateWGKey(k string) error {
	k = strings.TrimSpace(k)
	if k == "" {
		return fmt.Errorf("is empty")
	}
	raw, err := base64.StdEncoding.DecodeString(k)
	if err != nil {
		return fmt.Errorf("%q is not valid base64", k)
	}
	if len(raw) != 32 {
		return fmt.Errorf("%q decodes to %d bytes, want a 32-byte key", k, len(raw))
	}
	return nil
}

// validateHost32 requires a single-host /32 CIDR — exactly what an AllowedIPs
// entry for one device should be, and nothing that could smuggle a wider route
// or a shell metacharacter.
func validateHost32(cidr string) error {
	cidr = strings.TrimSpace(cidr)
	ip, ipnet, err := net.ParseCIDR(cidr)
	if err != nil {
		return fmt.Errorf("%q must be a single-host CIDR like 10.9.0.2/32: %w", cidr, err)
	}
	if ip.To4() == nil {
		return fmt.Errorf("%q must be an IPv4 /32", cidr)
	}
	ones, bits := ipnet.Mask.Size()
	if ones != 32 || bits != 32 {
		return fmt.Errorf("%q must be a /32 (a single host), not /%d", cidr, ones)
	}
	return nil
}

// ClientConfigParams describes the .conf a device imports.
type ClientConfigParams struct {
	PrivateKey          string   // the device's private key (delivered to the device once, via this config)
	Address             []string // device overlay addresses, e.g. ["10.9.0.2/32"]
	DNS                 []string // optional
	ServerPublicKey     string
	Endpoint            string   // host:port the device dials
	AllowedIPs          []string // what the device routes through the tunnel
	PersistentKeepalive int      // e.g. 25; 0 = omit
}

// RenderClientConfig builds the client .conf by constructing this package's own
// Config and calling Render — so the output round-trips through ParseConfig and
// stays the single wg-quick model the rest of the package speaks. Validate runs
// before returning: a .conf handed to a device that cannot bring a tunnel up is
// worse than an error here.
func RenderClientConfig(p ClientConfigParams) (string, error) {
	cfg := Config{
		Interface: Interface{
			PrivateKey: strings.TrimSpace(p.PrivateKey),
			Address:    p.Address,
			DNS:        p.DNS,
		},
		Peers: []Peer{{
			PublicKey:           strings.TrimSpace(p.ServerPublicKey),
			Endpoint:            strings.TrimSpace(p.Endpoint),
			AllowedIPs:          p.AllowedIPs,
			PersistentKeepalive: p.PersistentKeepalive,
		}},
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	return cfg.Render(), nil
}
